name: GCP Workload Identity PoC

on:
  push:
    branches:
      - main

jobs:
  deploy-to-gcs:
    runs-on: ubuntu-latest

    # Add permissions to request the OIDC token
    permissions:
      contents: read
      id-token: write

    steps:
    # Step 1: Checkout repository
    - name: 'Checkout repository'
      uses: 'actions/checkout@v4'

    # Step 2: Authenticate to Google Cloud
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/442678282814/locations/global/workloadIdentityPools/github-poc-pool/providers/github-provider'
        service_account: 'spoke-impersonation-sa@asml-gke-01.iam.gserviceaccount.com'

    # Step 3: Set up Cloud SDK (optional but good practice)
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    # Step 4: Use the authenticated credentials to access GCS
    - name: 'Write a file to GCS'
      run: |-
        echo "Hello from GitHub Actions, via WIF Hub-and-Spoke!" > proof.txt
        gsutil cp proof.txt gs://spoke-project-poc-bucket/proof.txt
