name: GCP Workload Identity PoC

on:
  push:
    branches:
      - main

jobs:
  deploy-to-gcs:
    runs-on: ubuntu-latest

    # Add permissions to request the OIDC token
    permissions:
      contents: read
      id-token: write

    steps:
    # THIS IS THE FIX: Add the checkout step first
    - name: 'Checkout repository'
      uses: 'actions/checkout@v4'

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        # The Workload Identity Provider resource name from your HUB project
        workload_identity_provider: 'projects/442678282814/locations/global/workloadIdentityPools/github-poc-pool/providers/github-provider'
        
        # The Service Account email from your SPOKE project
        service_account: 'spoke-impersonation-sa@asml-gke-01.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Write a file to GCS'
      run: |-
        echo "Hello from GitHub Actions, via WIF Hub-and-Spoke!" > proof.txt
        gsutil cp proof.txt gs://spoke-project-poc-bucket/proof.txt

